// <auto-generated />
using System;
using LR_3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LR_3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240426132604_AddStartData")]
    partial class AddStartData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LR_3.Models.LocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("LR_3.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kcal")
                        .HasColumnType("int");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65e22402-82db-496b-b7d6-400898bbd694"),
                            CreatedDate = new DateTime(2024, 4, 26, 16, 26, 3, 834, DateTimeKind.Local).AddTicks(725),
                            Description = "Description",
                            Kcal = 10,
                            Mass = 0.0,
                            Name = "Курячі яйця",
                            NumberOfProducts = 0
                        },
                        new
                        {
                            Id = new Guid("aee599b9-7f96-41fb-9d4e-af19acdfd94e"),
                            CreatedDate = new DateTime(2024, 4, 26, 16, 26, 3, 834, DateTimeKind.Local).AddTicks(778),
                            Description = "Description",
                            Kcal = 15,
                            Mass = 0.0,
                            Name = "Картопля",
                            NumberOfProducts = 0
                        },
                        new
                        {
                            Id = new Guid("afe7a16e-d41a-4326-8737-b842953d3cb8"),
                            CreatedDate = new DateTime(2024, 4, 26, 16, 26, 3, 834, DateTimeKind.Local).AddTicks(781),
                            Description = "Description",
                            Kcal = 25,
                            Mass = 0.0,
                            Name = "Цибуля",
                            NumberOfProducts = 0
                        });
                });

            modelBuilder.Entity("LR_3.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb46e0f1-7382-4ddb-a562-8257ea99d387"),
                            Description = "Description",
                            Name = "Яєчня",
                            ProductIds = "[\"65e22402-82db-496b-b7d6-400898bbd694\"]"
                        },
                        new
                        {
                            Id = new Guid("359eaff6-3a82-4486-8b7f-b99b8fe0afad"),
                            Description = "Description",
                            Name = "Картопля з цибулею",
                            ProductIds = "[\"aee599b9-7f96-41fb-9d4e-af19acdfd94e\",\"afe7a16e-d41a-4326-8737-b842953d3cb8\"]"
                        },
                        new
                        {
                            Id = new Guid("e454a1c9-20ef-4604-9f92-97641d00495d"),
                            Description = "Description",
                            Name = "Картопля з яйцем та цибулею",
                            ProductIds = "[\"65e22402-82db-496b-b7d6-400898bbd694\",\"aee599b9-7f96-41fb-9d4e-af19acdfd94e\",\"afe7a16e-d41a-4326-8737-b842953d3cb8\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
